parameters:
  # Adds a fallback DATABASE_URL
  env(DATABASE_URL): ''

doctrine:
  dbal:
    #configure these for your database server
    driver: 'pdo_mysql'
    server_version: '5.6'
    charset: utf8mb4
    schema_filter: '/^(?!\b(event_store)\b).*$/'

    url: '%env(resolve:DATABASE_URL)%'
    types:
      StraTDeS\SharedKernel\Infrastructure\Doctrine\CustomType\DoctrineUUIDV4: StraTDeS\SharedKernel\Infrastructure\Doctrine\CustomType\DoctrineUUIDV4
  orm:
    auto_generate_proxy_classes: '%kernel.debug%'
    naming_strategy: doctrine.orm.naming_strategy.underscore
    auto_mapping: true
    mappings:
      Suite_Domain:
        is_bundle: false
        type: yml
        dir: '%kernel.project_dir%/src/Infrastructure/Doctrine/Mapping/Domain'
        prefix: 'App\Domain'
      Suite_Application:
        is_bundle: false
        type: yml
        dir: '%kernel.project_dir%/src/Infrastructure/Doctrine/Mapping/Application'
        prefix: 'App\Application'
      Suite_Infrastructure:
        is_bundle: false
        type: yml
        dir: '%kernel.project_dir%/src/Infrastructure/Doctrine/Mapping/Infrastructure'
        prefix: 'App\Infrastructure'
      Suite_Shared_Kernel_Application:
        is_bundle: false
        type: yml
        dir: '%kernel.project_dir%/src/Infrastructure/Doctrine/Mapping/SharedKernel/Application'
        prefix: 'StraTDeS\SharedKernel\Application'